### PR TITLE
fix(click controls): don't collapse on all clicks

### LINKED ISSUE #28: Ouija closes on click
To reproduce, open a Ouija comment block and click a different trigger. Ouija should stay open and move to the triggered element instead of closing Ouija altogether.

### PR DESCRIPTION
**Pull request by colinmacdonald**
Closes #28 

Moves and improves the control click logic out of the conversation component so we can manage the global state of all conversations.
- If the currently active conversation's control is clicked the conversation closes.
- If conversation A is open and the user clicks conversation B's control, A closes and B opens.
- If the active conversation itself is clicked, it doesn't close
- If anywhere else on the document is clicked, the conversation will close.

### CODE REVIEW

File: app/ouija.jsx [hunk 1]
```diff
@@ -103,3 +119,49 @@ Ouija.prototype._renderSections = function() {
...
+};
+
+Ouija.prototype._handleCollapseClick = function(e) {
+  this._collapseCurrent();
+
+  this._el.article.removeClass(ACTIVE_CLASS);
+};
+
+Ouija.prototype._collapseCurrent = function() {
+  if (this._el.activeConversation) {
```
Comment (ianlivingstone) [inline app/ouija.jsx]: why not `if(!this._el.activeConversation) { return; }`

inverse the logic !

**Comment by ianlivingstone** [comment]
LGTM

File: app/ouija.jsx (hunk 1 above)
Comment (colinmacdonald) [inline app/ouija.jsx]: done.
